### ISSUE TITLE
NRF jammer failure to function in Bruce 1.15

### ISSUE THREAD

**Issue by prjamming** [BruceDevices/firmware#2475]
**Describe the bug:**
After updating to Bruce 1.15, NRF24 jamming no longer functions correctly. NRF spectrum analysis works normally, indicating NRF24 is communicating properly. Attempting to use the jammer results in nothing happening. If I enter and exit the options menu by pressing ok, channel switching animation slows and back button on top of T-Embed fails to function. Hard reset required to restore function. Switching back to 1.14 resolves issue.

**Steps To Reproduce:**

1. Flash Bruce 1.15
2. Open NRF24 tools
3. Run Spectrum Analyzer (works normally)
4. Run NRF Jammer
5. Observe jamming does not function
6. Enter Options and exit back to the jammer
7. Jammer animation becomes extremely slow and Bruce freezes after

* Device used:
  LILYGO T-Embed CC1101 with NRF24L01 module

**Expected behavior:**
NRF24 jammer should begin jamming normally without crashing, as observed in 1.14.

**Actual behavior:**
NRF spectrum works normally, but jammer functionality is broken. Entering/exiting Options partially changes behavior, causing jammer UI to move very slowly before Bruce freezes.

**Additional context / logs:**
Bruce 1.15 installed with Bmorcelli Launcher v2.7.2. Flashing directly from bruce.computer website results in same problem of jamming failing to function and Bruce freezing/crashing. Downgrading back to Bruce 1.14 immediately restores normal jammer functionality. For example, wireless earbuds and mouse stop functioning instantly upon starting jamming in 1.14, confirming software is the cause of the problem, not hardware.

**Comment by x-Felix** [comment]
I just upgraded my lilygo t-embed cc1101 plus to 1.15 version. 
Menu NRF24 -> Spectrum without issue. 
NRF24 -> NRF Jammer -> Full Spectrum / Wifi 2.4Ghz / BLE Data / BLE ADV / BT Classic / USB Dongles / ... which one you choose has issue? 
I chose BT Classic, then select SPI Mode, it runs fine.

**Comment by prjamming** [comment]
I have issues with all jamming options and spi/spi uart.

**Comment by xRoGx13** [comment]
I'm having the same issue with the NRF24L01+CC1101 Pingequa module on the Stick S3! I'm seeing the exact same behavior described above, but in my case the jammer function seems to be running at like 1% of the power it had in v1.14. I literally have to put the module antennas right next to the RX/TX device to get any signal interruption.

**Comment by pinchepasta** [comment]
This has been an issue for a while now, I posted it a while ago too. I just took the old nrf jammer and put it in 1.15 dev beta to fix that

**Comment by k13pt0One** [comment]
Title: T-Embed CC1101 Plus (3-Antenna Version) - NRF Failure After Updating to v1.15, Resolved by Full Erase + Downgrade to v1.14

Hardware:

* LilyGO T-Embed CC1101 Plus (3 external antenna version)
* ESP32-S3
* Integrated NRF24 module
* Integrated CC1101 module

Antenna Configuration:

* ESP32 Wi-Fi/Bluetooth antenna replaced with aftermarket 2.4 GHz antenna
* NRF24 antenna replaced with aftermarket 2.4 GHz antenna
* CC1101 antenna replaced with 915 MHz whip antenna

Issue Summary:
After updating from Bruce v1.14 to v1.15, NRF functionality appeared to stop working correctly.

Observed Behavior on v1.15:

* Wi-Fi scanning worked normally.
* Bluetooth scanning worked normally.
* NRF Spectrum Analyzer showed activity in the 2.4 GHz band.
* NRF-related features that previously worked no longer appeared to function correctly.
* Reverting to v1.14 without erasing storage did not resolve the issue.

Troubleshooting Performed:

* Swapped 2.4 GHz antennas between ESP32 and NRF SMA connectors.
* Verified Wi-Fi and Bluetooth operation remained normal.
* Opened device and inspected internal SMA pigtail connections.
* Tested NRF Spectrum Analyzer with NRF antenna connected and disconnected.

Spectrum Analyzer Findings:

* With the NRF antenna disconnected, the NRF spectrum display showed little to no activity.
* With the NRF antenna connected, the NRF spectrum display immediately showed significant 2.4 GHz activity.
* This suggests the NRF receive path, antenna, SMA connector, and pigtail were functioning and receiving RF energy.

Resolution:
Performed a complete firmware erase using the official Bruce flasher and then flashed v1.14.

Steps:

1. Selected "Erase Everything" in the Bruce web flasher.
2. Flashed Bruce v1.14.
3. Rebooted device.

Result:

* NRF functionality returned to normal operation.
* Behavior that was previously failing began working again.

Current Assessment:
This appears to be either:

* A v1.15 regression affecting NRF functionality, or
* A configuration/storage migration issue introduced during the update process.

Additional Notes:

* Prior downgrade attempts from v1.15 back to v1.14 without erasing storage did NOT fix the problem.
* Only a full erase followed by a clean v1.14 installation restored NRF functionality.
* RF/CC1101 functionality has not yet been fully retested on the clean v1.14 installation.
* Initial RF testing on v1.15 produced inconsistent results, but further testing is required before determining whether RF was affected by the same issue.

**Comment by Ninja-jr** [comment]
There was some reworking on the nrf24 functions on 1.15 if im not wrong looking at thePR's aswell as some works done to fix compilation errors that might have interfered on that.

**Comment by erickdeoliveiraleal** [comment]
Same here

**Comment by coolbeans87** [comment]
I've been experiencing similar issues with my LILYGO T-Embed CC1101 Plus device since upgrading to version 1.15. NRF jamming was functioning flawlessly on version 1.14, but now it does not work at all.

**Comment by Ninja-jr** [comment]
> I've been experiencing similar issues with my LILYGO T-Embed CC1101 Plus device since upgrading to version 1.15. NRF jamming was functioning flawlessly on version 1.14, but now it does not work at all.

I've seen people complaining lately about v 1.15 breaking the nrf jammer and i suspect it's due to some changes made since I last worked on it on version 1.14 which i tested and worked well...but sadly my 2 devices are permanently dead and so I can't test it as i won't risk to get something out not throughly tested. Let's hope one of the maintainers revert those changes to the nrf jammer or some dev finds the sollution. @bmorcelli maybe you could look into this?

**Comment by suarez-copilot5474** [comment]
Can anyone please let me know when this gets fixed?
Thankyou😊

**Comment by kingSt00** [comment]
I buy t embed cc1101 plus external antenna 
And I use Bruce firmware 1.15 NRF24 spectrum analysis working but WI FI JAMMING NOT WORKING BUT I use 1.14 spectrum analysis Working and WI FI Jamming work but BLUETOOTH JAMMING NOT BLE Data / BLE ADV / BT Classic / USB Dongles
Only WI FI 2.4 JAMMING WORK 
HOW TO FIX 🥲

**Comment by Ninja-jr** [comment]
Well on 1.15 some issues are being fixed on the beta version. For 1.14 from my experience, i get not such issues

**Comment by bmorcelli** [comment]
Yesterday I rolled back the NRF jamming function, only kept the random channel mode (FHSS) and frequency channels from the 1.15

I tested with my JBL earphones, and it worked as expected, although the "Bluetooth" Channel list doesn't work out as expected ("Ble adv pri" worked better than Bluetooth and BLEch modes)

I removed all those fancy (and useless) UI.. all those UI redrawing increase the time between hops, reducing the average noise generated by nrf24 while changing channels (which makes it effectively jam)

Same approach will be applied to RF

**Comment by Ninja-jr** [comment]
Indeed...why to change something that works fine? Specially if its to break it and use precious resources just for the sake of ui beautification? Imo the nrf jammer we had on 1.13-1.14 just worked as expected. The fact it didn't had a long range isn't Bruce's fault but rather nrf2401+ module limitations specially when using alone.

**Comment by Lorex122** [comment]
I tested the beta today on my JBL Flip 7. I’m using an M5Stack Stick S3 running the beta firmware. When I selected the NRF24 function, it showed the message “NRF24 pins undefined.” After confirming with OK, the function started but didn’t work properly. Only the Bluetooth mode worked once, and even then only at a very short range, very close to the device. Bruce v1.14 worked reliably (~10m indoor range), but the beta behaves differently. I am using the Pingequa RF board with a 5dbi Antenna

Do you have any idea how to fix this?
The beta version is 86eb576, if that’s relevant. I hope I provided useful information!

**Comment by Ninja-jr** [comment]
I think we need a full revert to the 1.14 version as it worked fine for sure. It's the same version i improved with some slight adjustments from @Senape3000. Yes new version has a sleek ui...but what's worth having such if it doesn't work  as it should? On embedded systems we often shall put functionality over screen beauty.
I think @bmorcelli should take a look into that again maybe and do a full revert? Just my opinion

**Comment by bmorcelli** [comment]
I did it Saturday night, it is on Beta for testing

**Comment by Lorex122** [comment]
What if we keep the Beta UI and the functions from 1.14 and dont use the functions nor the ui of 1.15?

**Comment by Senape3000** [comment]
Hi all, sorry for late response, i implemented nRF jammer on my EvilCrow project and works really well, i think this version need some fix, if someone can take a look this is the module [LINK](https://github.com/Senape3000/EvilCrowRF-V2/blob/main/src/modules/nrf/NrfJammer.cpp)
ATM im not on Bruce because of work, hope this help

**Comment by Ninja-jr** [comment]
It seems good indeed tho i cant test it but one could adapt that to Bruce
if we can't get it to work with the revert. My main issue is not having any
testing devices else id sure take a look into yhat and adapt it

**Comment by Lorex122** [comment]
Ill try and test it. How can I Flash the file?

**Comment by Senape3000** [comment]
> It seems good indeed tho i cant test it but one could adapt that to Bruce
> if we can't get it to work with the revert. My main issue is not having any
> testing devices else id sure take a look into yhat and adapt it
> 
> Le lun. 22 juin 2026, 18:11, Senape3000 ***@***.***> a écrit :
> […](#)

It's an esp32 too, i think it's a bug in the logic with bruce jammer, try to compare the 2 logic with codex (or similar), i remember was a simple fix to fix the Constant Carrier mode.

**Comment by Ninja-jr** [comment]
> Ill try and test it. How can I Flash the file?

Run a build on it . If needed, go to actions and run the build tembed cc1101 one since you have that device too.

**Comment by Ninja-jr** [comment]
> > It seems good indeed tho i cant test it but one could adapt that to Bruce
> > if we can't get it to work with the revert. My main issue is not having any
> > testing devices else id sure take a look into yhat and adapt it
> > 
> > Le lun. 22 juin 2026, 18:11, Senape3000 ***@***.***> a écrit :
> > […](#)
> 
> It's an esp32 too, i think it's a bug in the logic with bruce jammer, try to compare the 2 logic with codex (or similar), i remember was a simple fix to fix the Constant Carrier mode. 

Thing is codex isn't the magic trick tho it definitely can help but different language layers (c vs c+) and using nimble as we do might play a role in it. We have to work with what we have and make it work as good as we can

**Comment by Ninja-jr** [comment]
> > > It seems good indeed tho i cant test it but one could adapt that to Bruce
> > > if we can't get it to work with the revert. My main issue is not having any
> > > testing devices else id sure take a look into yhat and adapt it
> > > 
> > > Le lun. 22 juin 2026, 18:11, Senape3000 ***@***.***> a écrit :
> > > […](#)
> > 
> > It's an esp32 too, i think it's a bug in the logic with bruce jammer, try to compare the 2 logic with codex (or similar), i remember was a simple fix to fix the Constant Carrier mode. 
> 
> Thing is codex isn't the magic trick tho it definitely can help but different language layers (c vs c+) and using nimble as we do might play a role in it. We have to work with what we have and make it work as good as we can

Unless you want to migrate the whole Bluetooth code to bluedroid...i'll say...feel free to do that if you want...but isn't an easy task...I gave up after a while and there are very reasonable reasons for that

**Comment by Lorex122** [comment]
> > Ill try and test it. How can I Flash the file?
> 
> Run a build on it . If needed, go to actions and run the build tembed cc1101 one since you have that device too.

but i got a m5 stack stick s3?

**Comment by Ninja-jr** [comment]
> > > Ill try and test it. How can I Flash the file?
> > 
> > Run a build on it . If needed, go to actions and run the build tembed cc1101 one since you have that device too.
> 
> but i got a m5 stack stick s3?
> 

Try anyway but for what i know the s3 stick still givzs alotta issues

**Comment by Lorex122** [comment]
Can anyone make a version of bruce with the jamming files from senape3000 for the m5 stack stick s3? I have been trying for 2h now and cant get it to work plssss

**Comment by Ninja-jr** [comment]
> Can anyone make a version of bruce with the jamming files from senape3000 for the m5 stack stick s3? I have been trying for 2h now and cant get it to work plssss
> 

Have you tried release 1.14? Its exactly those files

**Comment by Ninja-jr** [comment]
> > Can anyone make a version of bruce with the jamming files from senape3000 for the m5 stack stick s3? I have been trying for 2h now and cant get it to work plssss
> > 
> 
> Have you tried release 1.14? Its exactly those files

1.13 is with my improvements but not sure if stick s3 compatibility was done by then. 1.14 is with @Senape3000 's improvements to my code and I think its stick s3 compatible if I'm not wrong

**Comment by Lorex122** [comment]
So 1.14 is the best version to use rn? And can anyone tell me why apple spam and Android spam BOTH dont work on 1.14?
Thanks!

**Comment by Ninja-jr** [comment]
> So 1.14 is the best version to use rn? And can anyone tell me why apple spam and Android spam BOTH dont work on 1.14?
> Thanks!
> 
> 

Well we hadn't found a way to get the fastpair and apple spam to work so far but I think I got a sollution to that by spoofing the icloud bind flag and a few other things. It's in test now and probably gonna be merged soon

**Comment by Lorex122** [comment]
Cool thanks for making all that!

**Comment by suarez-copilot5474** [comment]
Is it possible for someone to build a bin file that i can flash on my t embed c1101 plus which includes bruce 1.15 but just the nrf section should be from 1.14. Bruce 1.15 has some interesting things that aren't on 1.14 but the nrf jammer isnt working on 1.15 . I'd really appreciate it if someone could do this or share the file if someone already has.
Also, i know this isnt related to the nrf functions but can anyone recommend me or walk me through the process of getting a stronger ir transmitter on the t embed c1101 plus that would work from about 10m since the built in one work from a maximum of 3-4m for me?

**Comment by bmorcelli** [comment]
Have you tried Beta? It was built a few minutes ago with NRF24 rolled back

You can download the binary from the flasher webpage

**Comment by suarez-copilot5474** [comment]
should i download the bin file and flash it or just use web flasher directly?
I dont understand where beta version is

**Comment by bmorcelli** [comment]
> should i download the bin file and flash it or just use web flasher directly?
> I dont understand where beta version is

Whatever your heart tells you to do, brother.. both processess will have the same output..

Follow the steps to flash (Select Beta, Vendor. Device. And a big "DOWNLOAD FIRMWARE .BIN" Button will pop up

**Comment by suarez-copilot5474** [comment]
I went here https://github.com/BruceDevices/firmware/actions/runs/28015609765 and downloaded the one for my device and the jammer is working now.
Now i have to test other function over the span of a couple of days to see if they are functional.
Thanks

**Comment by Lorex122** [comment]
The new beta also doesnt work for blueooth jamming, same problem with the beta before that and 1.15... The NRF-Jammer also says that the NRF24 pins are undefined.

**Comment by Lorex122** [comment]
Update: The last beta from the 30.6 is working better with bluetooth jamming than in 1.14. New problem: The BadUSB does not work on the new beta but it does on 1.14.

**Comment by Ninja-jr** [comment]
> Update: The last beta from the 30.6 is working better with bluetooth jamming than in 1.14. New problem: The BadUSB does not work on the new beta but it does on 1.14.

Well that's good. I'll try to take a look into the bad usb maybe some time soon.

**Comment by Lorex122** [comment]
In the new beta, the jammer works as said, but the badusb function does NOT work

**Comment by Lorex122** [comment]
ok, the beta of today (4aca041) works perfectly, both functions perform really well!

**Comment by suarez-copilot5474** [comment]
the 4aca041 says expired,
What about Fix RF Ghosting
Build and Push Releases #1057: Commit 98f66df pushed by bmorcelli?

**Comment by bmorcelli** [comment]
It works too..

**Comment by suarez-copilot5474** [comment]
Haha, wasn't expecting the maintainer to reply. Thanks! I'll give it a try.

**Comment by Lorex122** [comment]
Can anybody explain why there is no RCSwitch bruteforce in the RF menu? If you could add that, it would help alot! Thank you in advance! And the tesla port opener worked in 1.14 and doesnt in the beta from 10.7. Pls try and fix that aswell althougg I dont have ANY idea why that might be
